### ISSUE TITLE
SOS Message

### ISSUE THREAD

**Issue by rghvnsh** [shahriarivari/Automatic-Modulation-Classification#1]
Good Morning

I am currently in the final year of my MTech program and working on my thesis, which involves implementing an Automatic Modulation Classification (AMC) project. I came across your GitHub repository and am using it to gain practical experience for my implementation, as none of my colleagues are working on AI projects, so I am learning independently.

I successfully ran the MATLAB code and generated the modulation_examples.mat file. I then used your packaging.ipynb code in Jupyter Notebook to convert the .mat file to modulation_examples.pkl.

Could you please guide me on the next steps for training the CNN model? Specifically, I would like to know if the data_setup.py and train_functions.py files are necessary, given that I am using datasets generated from MATLAB code instead of the RadioML dataset. If these files are required, how can I adapt them to work with the MATLAB-generated datasets?

I would greatly appreciate your assistance, as I need to present this project to my professor on November 20, 2024.

Thank you in advance for your help!

**Comment by shahriarivari** [comment]
Hello,

Frist good luck on your path and i'd be happy to help.

---------------------------------
### Notes on Matlab code:

I checked the Matlab code and did some small changes, i advise you to sync and generate the dataset again. If you have a nice GPU or using google colab I advise you to change the output frame length from 128 to any higher number ideally 1024, but you gonna need more computation power and change the CNN architecture accordingly.

I tired to recreate the RadioML dataset as close as possible and managed to find their channel coefficients from their github repo. you change these and plot the signals if necessary.

For plotting, after generating and before saving (comment the saving line), it would be helpful to plot some signals, here is the sample code : plot_example_signal(examples_dict, 'QPSK', 'pos18', 4), run this at the command window and check different signals, change the WLEN, and again plot them and see the difference, I have also attached some pictures so you can see the difference. The its a comparison between WLEN = 128 vs 1024

---------------------------------
### Notes on training a CNN:

For training you dont need to change much, but in these lines :
1 - data = load_data(path='RML2016.10a/RML2016.10a_dict.pkl') --> change the directory to the generated signals after packaging.

2- X_train , y_train , X_test , y_test, mods = load_digital_mods(data=data , ratio= 0.2) --> for this line change it to : 
X_train , y_train , X_test , y_test, mods = create_train_test_splits(data=data , ratio= 0.2).

I guess the rest wouldn't need change.

And as for CNN training you have to look for a overall 57 to 59 accuracy on train set and a little bit smaller on test test. And if you plot the Acc vs SNR at the end of the code you should see that the acc gets better in higher SNRs almost reaches 90 or more, depends on the CNN architecture but most of them reach 90 at SNR 18.

Different architectures could be found, I used a similar architecture as the same authors that generated the RadioML, they were to first to use CNN. but check the papers I have mentioned they could give you lots of insights.

The bottleneck in AMC is the miss-classification between QAMs they have a similar constellation even in high SNRs. 

If you have anymore questions, I would be happy to help.

![PAM_4_res_128_pos_18_SNR](https://github.com/user-attachments/assets/fb34119c-ebdf-4f61-8f99-29f4dabdcacf)
![PAM_4_res_1024_pos_18_SNR](https://github.com/user-attachments/assets/8dc36b4d-77b7-40f0-999a-407efb05e278)
![QPSK_res_128_pos_18_SNR](https://github.com/user-attachments/assets/55c8865f-1c39-4525-abe9-33a715b57a90)
![QPSK_res_1024_pos_18_SNR](https://github.com/user-attachments/assets/66a8c003-55d3-4135-a14d-b6dde57a4af7)

**Comment by rghvnsh** [comment]
Thank you so much for your prompt reply. 

I am new to the AI domain, and I am finding it challenging to understand and implement the Automatic Modulation Classification project. Would you be open to freelancing for this project?

**Comment by rghvnsh** [comment]
Based on the information from your GitHub link, here is what I understand:

1. Generate the 'modulation_examples.mat' file by running the MATLAB code successfully. (I made two modifications to your MATLAB code: first, changed 'QAM16' to 'QAM_16' and 'QAM64' to 'QAM_64' in the 'helperModGetModulator.m' and 'helperModGetSource.m' files; second, commented out the 'save' command). Since your MATLAB code has been updated, I will use that to generate the '.mat' file.

2. Use the Python code in the 'packaging.ipynb' file on Jupyter Notebook to convert the 'modulation_examples.mat' file into the 'modulation_examples.pkl' file.

3. Use the Python code in the 'CNN_training_validation.ipynb' file on Jupyter Notebook to load the data, fit the label encoder, convert the train and test arrays into tensors, create the model class, and train and validate the model.

There are also three other files: 'data_setup.py', 'train_functions.py', and 'utills.py'. The 'CNN_training_validation.ipynb' file uses these files for model training. I am a bit confused because the 'data_setup.py' file mentions that it "loads the RML2016 dataset," and the 'README.md' notes that "data_setup provides functions to import, filter, and create train and test splits specific to the RADIOML 2016.10a dataset." Since I am using a MATLAB-generated dataset, should any changes be made to the 'data_setup.py' file?
Please clarify if my understanding of the project is correct.

Also, I am not able to understand the line "I tired to recreate the RadioML dataset as close as possible and managed to find their channel coefficients from their github repo. you change these and plot the signals if necessary" mentioned in your response.

Requesting for your early guidance as I am running short of time to meet the deadline.

**Comment by shahriarivari** [comment]
the .py files are python scripts which is used in the jupyter notebook. the data_setup.py is to load and create train and test splits and other functionalities, also train functions include functions used in training. and when loading your generated matlab data there would be no issue since when packaging the generated data they are packaged similar to RadioML dataset.

As i said use import the "create_train_test_splits" function from the data_setup.py and after loading your generated dataset use the function to create train and test splits and the rest of the code is same mostly, note that if you change the output frame length in matlab from 128 to any number, when training your model you should change these lines : X_train = X_train.reshape(-1,1,2,128), X_test = X_test.reshape(-1,1,2,128) change the "128".

About the coefficients, when generating signals, each modulated signal has to pass through some filters, one of which is the channel, in order to generated signals as similar as the benchmark dataset which is RadioML, you have find the correct coefficients of the channels so the signals would go through the same channel impairments. I found the same coeffs as the authors of the RadioML dataset.

**Comment by rghvnsh** [comment]
Good Morning

I tried to implement the project based on your valuable inputs. I did below mentioned procedure:

Notes on MATLAB code-
1.	Generated 'modulation_examples.mat' file by running the updated MATLAB code. The size of .mat file is approx 37 GB.
2.	Changed WLEN (output frame length) to 1024 since working on Google Colab Pro (selected A100 GPU as hardware accelerator).

Notes on Pickle file-
1.	Converted 'modulation_examples.mat' file to 'modulation_examples.pkl' file by using packaging.ipynb python code on Google Colab Pro. The size of .pkl file is approx 39 GB.

Notes about other files-
1.	    I made following changes in python code of data_setup.py and utills.py files:
(a)	     Changed at 02 places value from 128 to 1024 in data_setup.py file.
(b)	     Changed at 08 places wherever 128 was mentioned to 1024 in utills.py file.
2.	Uploaded all files i.e. modulation_examples.mat, modulation_examples.mat, data_setup.py, train_function.py and utills.py on My Google drive.
3.	    Mounted My Google drive on Google Colab Pro for implementing the model.

Notes on Model Training- Using python code of CNN_training_validation.ipynb file

1.	Ran below code by making two changes as advised i.e. changed file path and changed to create_train_test_splits function – 

from data_setup import load_data , create_train_test_splits
data = load_data(path='/content/drive/MyDrive/modulation_examples.pkl')
X_train , y_train , X_test , y_test, mods = create_train_test_splits(data=data , ratio= 0.2)
print(f"shape of the train and test **samples** are --> {X_train.shape , X_test.shape}")
print(f"shape of the train and test **labels** are --> {y_train.shape , y_test.shape}")

Following error obtained-
ValueError Traceback (most recent call last)
<ipython-input-11-766462550e18> in <cell line: 4>()      2       
3 data = load_data(path='/content/drive/MyDrive/modulation_examples.pkl')----> 
4 X_train , y_train , X_test , y_test, mods = create_train_test_splits(data=data , ratio= 0.2)      
5 print(f"shape of the train and test **samples** are --> {X_train.shape , X_test.shape}")      
6 print(f"shape of the train and test **labels** are --> {y_train.shape , y_test.shape}")
ValueError: **not enough values to unpack (expected 5, got 4)**

Amended the line as-
X_train , y_train , X_test , y_test = create_train_test_splits(data=data , ratio= 0.2)

Output obtained-

shape of the train and test **samples** are --> ((16384000, 2, 128), (4096000, 2, 128))
shape of the train and test **labels** are --> ((2048000, 2), (512000, 2))

2.     Changed value from 128 to 1024 in below code as advised-
   
X_train = X_train.reshape(-1,1,2,1024)
X_test = X_test.reshape(-1,1,2,1024)
y_train_encoded = label_encoder.transform(y_train[:,0]).astype(np.float32)
y_test_encoded = label_encoder.transform(y_test[:,0]).astype(np.float32)

3.	 Ran below code-

cnn_model = CNNModel().to(device)
cnn_model.initialize_weights()
optimizer = optim.AdamW(cnn_model.parameters(), lr=learning_rate)

results = train(model=cnn_model, 
                train_dataloader = train_dataloader,
                test_dataloader = test_dataloader,
                optimizer=optimizer,
                criterion=loss_function, 
                epochs=NUM_EPOCHS,
                device=device)

Error obtained-

Mat1 and mat2 shapes cannot be multiplied (100 x 40960 and 5120 x 256)

Amended the value in following code wherein changed value to 40960 in nn.Linear of self.fc_layers and code ran successfully-

class CNNModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_block = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=256, kernel_size=(1, 3), padding='same'),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Conv2d(in_channels=256, out_channels=80, kernel_size=(2, 3), padding='same'),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.AvgPool2d(kernel_size = (2,2))
        )
        self.fc_layers = nn.Sequential(
            nn.Flatten(start_dim=1),
            nn.Linear(40960, 256),
            nn.ReLU(),
            nn.Linear(256, 8)
        )
    
    def filters_output(self,x):
        return self.conv_block(x)

    def initialize_weights(self):
        for module in self.modules():
            if isinstance(module, nn.Conv2d) or isinstance(module, nn.Linear):
                # Initialize weights using Xavier initialization
                init.xavier_uniform_(module.weight)
                # Initialize biases to zeros
                if module.bias is not None:
                    init.constant_(module.bias, 0.0)

    def forward(self, x):
        return self.fc_layers(self.conv_block(x))

4.	    Training Results-
100%  --------------------------------------  50/50 [00:01<00:00, 45.63it/s]
Epoch: 1 | train_loss: 2.1204 | train_acc: 0.0100 | test_loss: 1.7483 | test_acc: 0.1500
Epoch: 2 | train_loss: 1.6950 | train_acc: 0.2800 | test_loss: 1.7576 | test_acc: 0.0500
Epoch: 3 | train_loss: 1.7809 | train_acc: 0.1900 | test_loss: 1.7150 | test_acc: 0.3000
Epoch: 4 | train_loss: 1.6472 | train_acc: 0.1900 | test_loss: 1.7252 | test_acc: 0.1000
Epoch: 5 | train_loss: 1.6436 | train_acc: 0.2300 | test_loss: 1.7090 | test_acc: 0.1000
Epoch: 6 | train_loss: 1.6392 | train_acc: 0.2300 | test_loss: 1.6910 | test_acc: 0.3000
Epoch: 7 | train_loss: 1.6241 | train_acc: 0.3000 | test_loss: 1.6807 | test_acc: 0.3000
Epoch: 8 | train_loss: 1.5882 | train_acc: 0.2200 | test_loss: 1.6689 | test_acc: 0.3000
Epoch: 9 | train_loss: 1.5412 | train_acc: 0.3400 | test_loss: 1.6763 | test_acc: 0.0500
Epoch: 10 | train_loss: 1.5253 | train_acc: 0.1900 | test_loss: 1.6707 | test_acc: 0.0500
Epoch: 11 | train_loss: 1.4929 | train_acc: 0.5500 | test_loss: 1.6114 | test_acc: 0.2000
Epoch: 12 | train_loss: 1.4215 | train_acc: 0.4600 | test_loss: 1.5701 | test_acc: 0.3000
Epoch: 13 | train_loss: 1.3965 | train_acc: 0.3100 | test_loss: 1.6435 | test_acc: 0.1000
Epoch: 14 | train_loss: 1.2860 | train_acc: 0.8000 | test_loss: 1.7331 | test_acc: 0.0500
Epoch: 15 | train_loss: 1.2526 | train_acc: 0.5000 | test_loss: 1.6005 | test_acc: 0.2000
Epoch: 16 | train_loss: 1.1641 | train_acc: 0.6100 | test_loss: 1.5090 | test_acc: 0.3000
Epoch: 17 | train_loss: 1.0972 | train_acc: 0.5000 | test_loss: 2.2802 | test_acc: 0.1500
Epoch: 18 | train_loss: 1.1986 | train_acc: 0.7400 | test_loss: 1.9240 | test_acc: 0.1000
Epoch: 19 | train_loss: 0.9111 | train_acc: 0.7800 | test_loss: 1.8526 | test_acc: 0.3000
Epoch: 20 | train_loss: 1.1551 | train_acc: 0.2500 | test_loss: 1.7381 | test_acc: 0.3000
Epoch: 21 | train_loss: 0.7226 | train_acc: 0.8800 | test_loss: 2.1623 | test_acc: 0.1000
Epoch: 22 | train_loss: 0.8179 | train_acc: 0.7300 | test_loss: 2.0531 | test_acc: 0.1000
Epoch: 23 | train_loss: 0.6469 | train_acc: 0.8700 | test_loss: 1.6557 | test_acc: 0.2500
Epoch: 24 | train_loss: 0.4248 | train_acc: 1.0000 | test_loss: 1.6689 | test_acc: 0.3500
Epoch: 25 | train_loss: 0.5313 | train_acc: 0.9300 | test_loss: 1.5998 | test_acc: 0.4500
Epoch: 26 | train_loss: 0.4181 | train_acc: 1.0000 | test_loss: 1.5698 | test_acc: 0.2500
Epoch: 27 | train_loss: 0.2379 | train_acc: 1.0000 | test_loss: 1.9329 | test_acc: 0.1000
Epoch: 28 | train_loss: 0.2499 | train_acc: 1.0000 | test_loss: 2.1752 | test_acc: 0.1000
Epoch: 29 | train_loss: 0.2273 | train_acc: 1.0000 | test_loss: 1.9291 | test_acc: 0.2000
Epoch: 30 | train_loss: 0.1139 | train_acc: 1.0000 | test_loss: 1.7025 | test_acc: 0.4500
Epoch: 31 | train_loss: 0.0629 | train_acc: 1.0000 | test_loss: 1.8755 | test_acc: 0.4000
Epoch: 32 | train_loss: 0.0826 | train_acc: 1.0000 | test_loss: 1.9810 | test_acc: 0.4000
Epoch: 33 | train_loss: 0.0785 | train_acc: 1.0000 | test_loss: 1.7602 | test_acc: 0.4000
Epoch: 34 | train_loss: 0.0238 | train_acc: 1.0000 | test_loss: 1.6934 | test_acc: 0.4000
Epoch: 35 | train_loss: 0.0096 | train_acc: 1.0000 | test_loss: 2.0020 | test_acc: 0.1500
Epoch: 36 | train_loss: 0.0108 | train_acc: 1.0000 | test_loss: 2.5473 | test_acc: 0.1000
Epoch: 37 | train_loss: 0.0167 | train_acc: 1.0000 | test_loss: 2.9822 | test_acc: 0.1000
Epoch: 38 | train_loss: 0.0193 | train_acc: 1.0000 | test_loss: 3.0889 | test_acc: 0.1000
Epoch: 39 | train_loss: 0.0141 | train_acc: 1.0000 | test_loss: 2.8956 | test_acc: 0.1000
Epoch: 40 | train_loss: 0.0054 | train_acc: 1.0000 | test_loss: 2.6090 | test_acc: 0.1500
Epoch: 41 | train_loss: 0.0024 | train_acc: 1.0000 | test_loss: 2.3682 | test_acc: 0.1500
Epoch: 42 | train_loss: 0.0009 | train_acc: 1.0000 | test_loss: 2.2542 | test_acc: 0.3500
Epoch: 43 | train_loss: 0.0005 | train_acc: 1.0000 | test_loss: 2.2785 | test_acc: 0.4000
Epoch: 44 | train_loss: 0.0005 | train_acc: 1.0000 | test_loss: 2.4125 | test_acc: 0.4500
Epoch: 45 | train_loss: 0.0007 | train_acc: 1.0000 | test_loss: 2.6130 | test_acc: 0.4500
Epoch: 46 | train_loss: 0.0008 | train_acc: 1.0000 | test_loss: 2.8390 | test_acc: 0.4000
Epoch: 47 | train_loss: 0.0012 | train_acc: 1.0000 | test_loss: 3.0494 | test_acc: 0.3500
Epoch: 48 | train_loss: 0.0020 | train_acc: 1.0000 | test_loss: 3.2024 | test_acc: 0.3500
Epoch: 49 | train_loss: 0.0017 | train_acc: 1.0000 | test_loss: 3.2804 | test_acc: 0.3500
Epoch: 50 | train_loss: 0.0016 | train_acc: 1.0000 | test_loss: 3.2911 | test_acc: 0.3500

5.      Plots (Photo attached)

Requesting to provide early clarification as per heads which I have mentioned in my query.

Thanking you in advance.
![Proj_Plot](https://github.com/user-attachments/assets/2790ad58-7956-4ab7-bcb9-03315341ee81)

**Comment by shahriarivari** [comment]
I am wondering why after changing the WLEN from 128 to 1024 and generating higher resolution samples, you still got 2 by 128 samples when creating train and test. it should be  (-1, 2, 1024), but for example you are still getting (16384000, 2, 128), and that is why the model cant learn. check the shapes again please , and then train the model. 
And when you make changes in the python scripts you should reset the kernel, I think thats what happened, when you changed the shapes in data_setup.py and ran the code it was using the old version of the data_setup.py and made 2 by 128 samples.
Check these and make sure you have the right shapes.
Then try to train the model, note the model's accuracy and loss shapes should have a similar shape to ones i provided in the code.
Since the inputs have more dimensions you will see this model is relatively small and you have to add cnn block and some linear layers to the fc part.
So at first try smaller epochs like 10 to 20 and check the trend of the loss and accuracy. if you could see a mostly steady downwards trend in loss and upwards in accuracy you are going to the right direction (in both train and test). Note that the test loss should not be smaller than train loss and not too much higher, should be as close and a bit higher. as in accuracy it should not get over the train acc plot line and no to far apart (check the plots in the code).
If the loss and accuracy numbers are same in 5-10 epochs and more it means the model cant learn and optimize it weights and try add more layers and cnn blocks and check again.

**Comment by rghvnsh** [comment]
Good Morning

1. Following your advice "When you make changes in the python scripts you should reset the kernel, I think thats what happened, when you changed the shapes in data_setup.py and ran the code it was using the old version of the data_setup.py and made 2 by 128 samples. Check these and make sure you have the right shapes," I reran the process after resetting the kernel. Now, I am able to obtain 2 by 1024 samples when creating the train and test datasets.

from data_setup import load_data , create_train_test_splits

data = load_data(path='/content/drive/MyDrive/modulation_examples.pkl')
X_train , y_train , X_test , y_test = create_train_test_splits(data=data , ratio= 0.2)
print(f"shape of the train and test **samples** are --> {X_train.shape , X_test.shape}")
print(f"shape of the train and test **labels** are --> {y_train.shape , y_test.shape}")

Output
shape of the train and test **samples** are --> ((2048000, 2, 1024), (512000, 2, 1024))
shape of the train and test **labels** are --> ((2048000, 2), (512000, 2))

2. Following your advice "Try to train the model, note the model's accuracy and loss shapes should have a similar shape to ones i provided in the code. Since the inputs have more dimensions you will see this model is relatively small and you have to add cnn block and some linear layers to the fc part," I attempted to modify the model by adding CNN blocks, increasing the number of linear layers in the fully connected part, varying dropout rates and tweaking the learning rate. However, despite trying various permutations and combinations, I have been unable to achieve the desired training results and plots.

Could you provide guidance on these two points:

1. Confirm if the train and test samples I obtained are correct.
2. Assist me in refining the model further to achieve better results, considering the adjustments I have already attempted.

Requesting for your early guidance on the above highlighted points.

**Comment by shahriarivari** [comment]
Hello,
Well yes the train and test samples are now in the right shape.
As in model refinements, you try bigger kernel sizes at early CNN blocks and lower it down as you reach to the lower layers. since you are using 2 by 1024 matrices, for example, start with 1 x 16 and then lower it down gradually to 2 x 4 , also consider using pooling layers so the dimensions would become smaller.
Make some changes and then train the model for 10 epochs (or a bit more or less), if you spot a substantial drop in Loss numbers then you are going to the right direction. These early drops in training loss and testing loss is a good indicator that the model is good enough. then change epochs to 50 and monitor the results.

**Comment by rghvnsh** [comment]
[CNN_training_validation.ipynb - Copy.docx](https://github.com/user-attachments/files/17964785/CNN_training_validation.ipynb.-.Copy.docx)

Good Morning

I am trying to implement the CNN model for 6 modulation schemes excluding QAM16 and QAM64.  There are few points for consideration and clarification:-
1. I have made necessary changes in MATLAB code to generate dataset for only 6 modulation schemes.
2. Updated the final fully connected layer in the CNN model to output the correct number of classes (6 instead of 8).
3. Calculated only for 8 epochs as just wanted to check the model.
4. Will any changes to be made in other files like data_setup.py, train_functions.py and utills.py or any changes to be made in CNN_training_validation code.
5. Value of WLEN take as 128.
6. I am receiving error while creating the Confusion matrix (Refer attached file).

Requesting for your early guidance on the above highlighted points.

**Comment by shahriarivari** [comment]
Hello,
I saw the loss and accuracy curves and they look okay. the error you are receiving is because it tries to divide a number by zero, in this line : cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100, check the cm value before this line and see why you have zero in the denominator.
Also i saw you normalized the dataset, the matlab code already has normalized it, it wont be necessary. and after creating test and train splits , print the labels and make sure u have 6 , or when fitting the label encoder print the class names and make sure there are 6.

**Comment by rghvnsh** [comment]
Thank you for the reply.

[Query_30 Nov.docx](https://github.com/user-attachments/files/17966298/Query_30.Nov.docx)

Please refer to the attached file for the following point: "After creating test and train splits, print the labels and make sure there are 6 classes or, when fitting the label encoder print the class names and verify that there are 6." Kindly confirm if everything is correct.

Additionally, I need assistance resolving the following error:  
"The error you are receiving is because it tries to divide a number by zero, in this line:  
`cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100`.  
Check the cm value before this line and see why you have zero in the denominator."  

This error also arises when running the code for 8 modulation schemes and I am unable to decode the error.

Your valuable guidance would be greatly appreciated as I need to submit the results including the model training outcomes, accuracy vs SNR plot and confusion matrix by tonight without fail.

**Comment by shahriarivari** [comment]
this line makes the confusion matrix lines add up to 100 percent, try commenting it and then run it it should work.
and or put a print statement before this line and try to see why you get zeros from cm.sum(). or as I said you can ignore this line and only use "cm = confmat_tensor.cpu().numpy()".

**Comment by rghvnsh** [comment]
Thank you for the help.
![1](https://github.com/user-attachments/assets/464505a2-f0eb-4c6a-bb34-b54c3d5ca988)
![2](https://github.com/user-attachments/assets/c5ce4b03-de01-4700-867e-10a7292c929a)
![3](https://github.com/user-attachments/assets/06060852-cdb4-404f-be62-6db0d8e0469a)

I trained a model using a dataset generated from MATLAB code, focusing on 6 modulation schemes excluding 16QAM and 64QAM. The overall accuracy achieved is 52.01%. 

Attached are the training plots and the Accuracy vs. SNR plot for your reference.

Kindly review the results and provide feedback on whether the performance is satisfactory.

**Comment by shahriarivari** [comment]
Hello,
Well-done ! , 
Last figure's title should be "Train and Tess accuracy* ...".

And you can see the test lost and accuracy curves are below and over the train curves; you might think the model might have over fitted a little bit, but since you are using dropout layers in training phase, the loss is a bit higher and accuracy a bit lower than when model is in test mode, when model is in inference mode the dropout layers are disabled.

So all in all it looks good.

**Comment by rghvnsh** [comment]
Thank you for your continued assistance.

Request to provide clarifications on the following points to enhance my understanding of the subject:

1. The MATLAB code appears to have considered a SISO (Single Input and Single Output) scenario, rather than a MIMO (Multiple Input and Multiple Output) setup, for dataset generation. Could you confirm this?
2. Could you elaborate on the feature extraction process implemented in your CNN model? Specifically, what features are extracted and how?
3. What type of input is provided to the CNN model? Is it in the form of I/Q samples?

Your valuable guidance would be greatly appreciated.

**Comment by shahriarivari** [comment]
Well yes it is a SISO scenario when generating dataset,
The input are I/Q samples which you choose to be 2 by 128 for each modulation. and in terms of feature extractors, well there are the CNN blocks but it is hard to get a understanding out of them unlike in vision or image processing tasks.
But for visualization there is a paper you can check, "https://arxiv.org/abs/1602.04105",  under section 4.4 "Learned Features" you can see the authors have visualized the Convolution layers after training, I hope this gives you some insights.
